'''
This script generates plots demonstrating the translational invariance of the
spin-spin correlators. Uses data generated by hs_corr.jl.

Author: Lucas Z. Brito
'''

import matplotlib.pyplot as plt 
import pandas as pd 
import random

data_dir = '../data/hs/'
out_dir = '../figs/'

n = 10
r_max = 6
fig, ax = plt.subplots() 
for r in range(1, r_max):
	df = pd.read_csv(data_dir + f'dot_corr_trans_n={n}_r={r}.csv')
	i = df['i'].to_numpy().astype('|S1')
	print(i)

	dot_corr = df['dot_corr_re'].to_numpy()
	
	j = random.random() * 0.01
	ax.scatter(i, dot_corr + j, label=f'$\Delta r = {r}$')

ax.vlines([b'1'], *ax.get_ylim(), linestyle='dashed', color='black', label='Boundary')
plt.legend()
plt.title(f'$\langle\mathbf{{S}}_i \cdot \mathbf{{S}}_{{i+\Delta r}} \\rangle$, ' +\
	f'$N={n}$ (jittered)')
ax.set_xlabel('$i$')

plt.savefig(out_dir + f'hs_dot_corr_trans_n={n}.pdf')
plt.savefig(out_dir + f'hs_dot_corr_trans_n={n}.png', dpi=300)

